name: Deploy Django App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from GitHub
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}  # Your EC2 public DNS: ec2-52-54-98-30.compute-1.amazonaws.com
          username: ${{ secrets.EC2_USER }}  # Set to 'ubuntu'
          key: ${{ secrets.EC2_KEY }}  # Set to the content of your test-cicd-deployment-kp.pem file
          port: 22
          script: |
            cd ~/Git/project  # Update to your project directory
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart nginx
